### ISSUE TITLE
Does not work properly with ghidra server

### ISSUE THREAD

**Issue by rbaas293** [sengi12/ghidra-hexEditor#1]
When working on a team project the binary is not loaded into the hex editor. The editor tries to pull the file from the original upload path, which does not exist if originally uploaded from a local directory of another user.

**Comment by sengi12** [comment]
This is true. As of right now, the way I'm fetching the bytes for the file is by using java's built in [File](https://docs.oracle.com/javase/7/docs/api/java/io/File.html) class. I suppose in a case like that I would have to fetch the file bytes from the ghidra API if the path doesn't exist. This is something I can work on for a future update. Thanks.

**Comment by sengi12** [comment]
Just added an export functionality. When you are in using a ghidra server, the file is not saved locally. This new feature allows you to export the file from ghidra locally wherever you want and edit the binary from there. I'm going to close this issue.

**Comment by rbaas293** [comment]
Good work, thank you good sir!
